/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuditSchema extends BaseModel {
  static $columns = [
    'actorId',
    'actorLabel',
    'actorType',
    'auditableId',
    'auditableType',
    'correlationId',
    'createdAt',
    'event',
    'hash',
    'httpMethod',
    'id',
    'ipAddress',
    'metadata',
    'newValues',
    'oldValues',
    'prevHash',
    'requestId',
    'schemaVersion',
    'seq',
    'stream',
    'tags',
    'tenantId',
    'url',
    'userAgent',
  ] as const
  $columns = AuditSchema.$columns
  @column()
  declare actorId: string | null
  @column()
  declare actorLabel: string | null
  @column()
  declare actorType: string | null
  @column()
  declare auditableId: string | null
  @column()
  declare auditableType: string | null
  @column()
  declare correlationId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare event: string
  @column()
  declare hash: string
  @column()
  declare httpMethod: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare metadata: any | null
  @column()
  declare newValues: any | null
  @column()
  declare oldValues: any | null
  @column()
  declare prevHash: string
  @column()
  declare requestId: string | null
  @column()
  declare schemaVersion: string
  @column()
  declare seq: bigint | number
  @column()
  declare stream: string
  @column()
  declare tags: any
  @column()
  declare tenantId: string | null
  @column()
  declare url: string | null
  @column()
  declare userAgent: string | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InvoiceSchema extends BaseModel {
  static $columns = [
    'amount',
    'createdAt',
    'iban',
    'id',
    'reference',
    'status',
    'updatedAt',
  ] as const
  $columns = InvoiceSchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare iban: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reference: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
